<?php
namespace Controllers; use Core\Controller; use Core\Auth; use Models\Vehicle; use Models\AuditLog; use Helpers\CSRF;

class VehicleController extends Controller {
    public function index(){ Auth::requireLogin(); $filters=['jenis'=>$_GET['jenis']??'','status_kendaraan'=>$_GET['status_kendaraan']??'','status_pajak'=>$_GET['status_pajak']??'','penanggung'=>$_GET['penanggung']??'']; $vehicles = Vehicle::all($filters); $this->render('vehicle/index', compact('vehicles','filters')); }
    public function create(){ Auth::requireAdmin(); $this->render('vehicle/create'); }
    public function store(){ Auth::requireAdmin(); if(!CSRF::check($_POST['csrf'] ?? '')) die('CSRF invalid'); $foto_path=null; if(!empty($_FILES['foto']['name'])){ $name = time() . '_' . preg_replace('/[^a-zA-Z0-9_.-]/','', $_FILES['foto']['name']); $target = UPLOAD_DIR . '/' . $name; if(!is_dir(UPLOAD_DIR)) mkdir(UPLOAD_DIR,0777,True); move_uploaded_file($_FILES['foto']['tmp_name'],$target); $foto_path='/assets/uploads/vehicles/' . $name; } $data=['plat'=>$_POST['plat'],'merk'=>$_POST['merk'],'tipe'=>$_POST['tipe'],'tahun'=>$_POST['tahun'],'jenis'=>$_POST['jenis'],'status_penggunaan'=>$_POST['status_penggunaan'],'status_kendaraan'=>$_POST['status_kendaraan'],'foto_path'=>$foto_path,'current_responsible'=>$_POST['current_responsible']]; $id=Vehicle::create($data); AuditLog::log('create','vehicles',$id,$data); header('Location: /vehicles'); }
    public function edit(){ Auth::requireAdmin(); $v=Vehicle::find($_GET['id']); $this->render('vehicle/edit', compact('v')); }
    public function update(){ Auth::requireAdmin(); if(!CSRF::check($_POST['csrf'] ?? '')) die('CSRF invalid'); $id=$_POST['id']; $v=Vehicle::find($id); $foto_path=$v['foto_path']; if(!empty($_FILES['foto']['name'])){ $name=time() . '_' . preg_replace('/[^a-zA-Z0-9_.-]/','', $_FILES['foto']['name']); $target=UPLOAD_DIR . '/' . $name; move_uploaded_file($_FILES['foto']['tmp_name'],$target); $foto_path='/assets/uploads/vehicles/' . $name; } $data=['plat'=>$_POST['plat'],'merk'=>$_POST['merk'],'tipe'=>$_POST['tipe'],'tahun'=>$_POST['tahun'],'jenis'=>$_POST['jenis'],'status_penggunaan'=>$_POST['status_penggunaan'],'status_kendaraan'=>$_POST['status_kendaraan'],'foto_path'=>$foto_path,'current_responsible'=>$_POST['current_responsible']]; Vehicle::update($id,$data); AuditLog::log('update','vehicles',$id,$data); header('Location: /vehicles'); }
    public function delete(){ Auth::requireAdmin(); if(!CSRF::check($_POST['csrf'] ?? '')) die('CSRF invalid'); $id=$_POST['id']; Vehicle::delete($id); AuditLog::log('delete','vehicles',$id,[]); header('Location: /vehicles'); }
    public function show(){ Auth::requireLogin(); $v=Vehicle::find($_GET['id']); $this->render('vehicle/show', compact('v')); }
}
